service: sat-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

package:
  individually: true

functions:
  api:
    handler: index.handler
    package:
      artifact: ../packages/api/dist/api.zip
  ingest:
    handler: index.handler
    package:
      artifact: ../packages/ingest/dist/ingest.zip
