on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: test
      working-directory: .
      run: |
        ls
        yarn run test
