on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
    - name: test
      run: yarn run test
      working-directory: ..
