on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        npm install
        npm run test
      working-directory: ./stac-api
