on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: install node
      uses: actions/setup-node@master
      with:
        version: 10.15

    - name: yarn install
      run: yarn install

    - name: yarn test
      run: yarn test

